pipeline {
    agent any

    stages {
        stage('Clone repository') {
            steps {
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[url: 'https://github.com/vnk123/PES1UG21CS706_Jenkins.git']],
                    scriptPath: 'Jenkins_lab-main/main'
                ])
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'g++ hello.cpp -o output'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh './output'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    echo 'Deployment step'
                }
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed'
        }
    }
}
